In [1]:
import pandas as pd

In [2]:
fr=pd.read_csv("train.csv")

In [3]:
fr

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,1,2596,51,3,258,0,510,221,232,148,...,0,0,0,0,0,0,0,0,0,5
1,2,2590,56,2,212,-6,390,220,235,151,...,0,0,0,0,0,0,0,0,0,5
2,3,2804,139,9,268,65,3180,234,238,135,...,0,0,0,0,0,0,0,0,0,2
3,4,2785,155,18,242,118,3090,238,238,122,...,0,0,0,0,0,0,0,0,0,2
4,5,2595,45,2,153,-1,391,220,234,150,...,0,0,0,0,0,0,0,0,0,5
5,6,2579,132,6,300,-15,67,230,237,140,...,0,0,0,0,0,0,0,0,0,2
6,7,2606,45,7,270,5,633,222,225,138,...,0,0,0,0,0,0,0,0,0,5
7,8,2605,49,4,234,7,573,222,230,144,...,0,0,0,0,0,0,0,0,0,5
8,9,2617,45,9,240,56,666,223,221,133,...,0,0,0,0,0,0,0,0,0,5
9,10,2612,59,10,247,11,636,228,219,124,...,0,0,0,0,0,0,0,0,0,5
10,11,2612,201,4,180,51,735,218,243,161,...,0,0,0,0,0,0,0,0,0,5
11,12,2886,151,11,371,26,5253,234,240,136,...,0,0,0,0,0,0,0,0,0,2
12,13,2742,134,22,150,69,3215,248,224,92,...,0,0,0,0,0,0,0,0,0,2
13,14,2609,214,7,150,46,771,213,247,170,...,0,0,0,0,0,0,0,0,0,5
14,15,2503,157,4,67,4,674,224,240,151,...,0,0,0,0,0,0,0,0,0,5
15,16,2495,51,7,42,2,752,224,225,137,...,0,0,0,0,0,0,0,0,0,5
16,17,2610,259,1,120,-1,607,216,239,161,...,0,0,0,0,0,0,0,0,0,5
17,18,2517,72,7,85,6,595,228,227,133,...,0,0,0,0,0,0,0,0,0,5
18,19,2504,0,4,95,5,691,214,232,156,...,0,0,0,0,0,0,0,0,0,5
19,20,2503,38,5,85,10,741,220,228,144,...,0,0,0,0,0,0,0,0,0,5
20,21,2501,71,9,60,8,767,230,223,126,...,0,0,0,0,0,0,0,0,0,5
21,22,2880,209,17,216,30,4986,206,253,179,...,0,0,0,0,0,0,0,0,0,2
22,23,2768,114,23,192,82,3339,252,209,71,...,0,0,0,0,0,0,0,0,0,5
23,24,2511,54,8,124,0,638,225,222,130,...,0,0,0,0,0,0,0,0,0,5
24,25,2507,22,9,120,14,732,215,221,143,...,0,0,0,0,0,0,0,0,0,5
25,26,2492,135,6,0,0,860,229,237,142,...,0,0,0,0,0,0,0,0,0,5
26,27,2489,163,10,30,-4,849,230,243,145,...,0,0,0,0,0,0,0,0,0,5
27,28,2962,148,16,323,23,5916,240,236,120,...,0,0,0,0,0,0,0,0,0,2
28,29,2811,135,1,212,30,3670,220,238,154,...,0,0,0,0,0,0,0,0,0,2
29,30,2739,117,24,127,53,3281,253,210,71,...,0,0,0,0,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15090,15091,2417,194,21,42,12,1154,211,252,165,...,0,0,0,0,0,0,0,0,0,3
15091,15092,2614,4,18,150,58,1347,193,201,143,...,0,0,0,0,0,0,0,0,0,3
15092,15093,2529,43,33,319,122,1293,205,148,54,...,0,0,0,0,0,0,0,0,0,3
15093,15094,2404,194,4,0,0,1154,219,243,160,...,0,0,0,0,0,0,0,0,0,6
15094,15095,2426,14,30,67,20,1071,178,166,111,...,0,0,0,0,0,0,0,0,0,6
15095,15096,2410,19,22,30,10,1006,197,186,119,...,0,0,0,0,0,0,0,0,0,6
15096,15097,2478,38,32,192,77,1110,203,154,66,...,0,0,0,0,0,0,0,0,0,6
15097,15098,2653,343,10,192,41,1216,200,225,163,...,0,0,0,0,0,0,0,0,0,3
15098,15099,2661,8,7,234,45,1158,212,226,152,...,0,0,0,0,0,0,0,0,0,3
15099,15100,2514,34,33,256,110,1015,195,150,69,...,0,0,0,0,0,0,0,0,0,6
15100,15101,2519,341,22,467,118,1006,168,201,169,...,0,0,0,0,0,0,0,0,0,3
15101,15102,2496,32,23,150,-22,883,208,182,99,...,0,0,0,0,0,0,0,0,0,6
15102,15103,2576,43,21,283,-23,953,219,189,96,...,0,0,0,0,0,0,0,0,0,3
15103,15104,2563,23,31,85,-10,816,186,158,91,...,0,0,0,0,0,0,0,0,0,6
15104,15105,2566,259,10,421,-33,853,196,246,189,...,0,0,0,0,0,0,0,0,0,3
15105,15106,2480,10,21,150,38,607,193,194,133,...,0,0,0,0,0,0,0,0,0,6
15106,15107,2656,66,11,524,35,883,231,217,117,...,0,0,0,0,0,0,0,0,0,3
15107,15108,2600,293,14,330,0,812,179,236,197,...,0,0,0,0,0,0,0,0,0,3
15108,15109,2593,38,21,120,-6,769,215,190,101,...,0,0,0,0,0,0,0,0,0,3
15109,15110,2600,57,19,0,0,731,229,197,93,...,0,0,0,0,0,0,0,0,0,6
15110,15111,2508,33,26,67,1,644,204,173,91,...,0,0,0,0,0,0,0,0,0,6
15111,15112,2610,59,17,60,10,674,231,202,98,...,0,0,0,0,0,0,0,0,0,6
15112,15113,2600,38,25,124,0,589,212,178,89,...,0,0,0,0,0,0,0,0,0,6
15113,15114,2688,104,15,443,10,805,245,219,99,...,0,0,0,0,0,0,0,0,0,3
15114,15115,2670,108,12,624,24,730,241,225,112,...,0,0,0,0,0,0,0,0,0,3
15115,15116,2607,243,23,258,7,660,170,251,214,...,0,0,0,0,0,0,0,0,0,3
15116,15117,2603,121,19,633,195,618,249,221,91,...,0,0,0,0,0,0,0,0,0,3
15117,15118,2492,134,25,365,117,335,250,220,83,...,0,0,0,0,0,0,0,0,0,3
15118,15119,2487,167,28,218,101,242,229,237,119,...,0,0,0,0,0,0,0,0,0,3
15119,15120,2475,197,34,319,78,270,189,244,164,...,0,0,0,0,0,0,0,0,0,3

In [4]:
fr.describe()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,15120.00000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,...,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000,15120.000000
mean,7560.50000,2749.322553,156.676653,16.501587,227.195701,51.076521,1714.023214,212.704299,218.965608,135.091997,...,0.045635,0.040741,0.001455,0.006746,0.000661,0.002249,0.048148,0.043452,0.030357,4.000000
std,4364.91237,417.678187,110.085801,8.453927,210.075296,61.239406,1325.066358,30.561287,22.801966,45.895189,...,0.208699,0.197696,0.038118,0.081859,0.025710,0.047368,0.214086,0.203880,0.171574,2.000066
min,1.00000,1863.000000,0.000000,0.000000,0.000000,-146.000000,0.000000,0.000000,99.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,3780.75000,2376.000000,65.000000,10.000000,67.000000,5.000000,764.000000,196.000000,207.000000,106.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,7560.50000,2752.000000,126.000000,15.000000,180.000000,32.000000,1316.000000,220.000000,223.000000,138.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
75%,11340.25000,3104.000000,261.000000,22.000000,330.000000,79.000000,2270.000000,235.000000,235.000000,167.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000
max,15120.00000,3849.000000,360.000000,52.000000,1343.000000,554.000000,6890.000000,254.000000,254.000000,248.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

In [5]:
fr.isnull().sum()

Id                                    0
Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0
Soil_Type11                           0
Soil_Type12                           0
Soil_Type13                           0
Soil_Type14                           0
Soil_Type15                           0
Soil_Type16                           0
Soil_Type17                           0
Soil_Type18                           0
Soil_Type19                           0
Soil_Type20                           0
Soil_Type21                           0
Soil_Type22                           0
Soil_Type23                           0
Soil_Type24                           0
Soil_Type25                           0
Soil_Type26                           0
Soil_Type27                           0
Soil_Type28                           0
Soil_Type29                           0
Soil_Type30                           0
Soil_Type31                           0
Soil_Type32                           0
Soil_Type33                           0
Soil_Type34                           0
Soil_Type35                           0
Soil_Type36                           0
Soil_Type37                           0
Soil_Type38                           0
Soil_Type39                           0
Soil_Type40                           0
Cover_Type                            0
dtype: int64

In [6]:
tr=fr.drop(columns=['Id','Cover_Type'])

tr.columns

In [7]:
tr.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10',
       'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14',
       'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18',
       'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22',
       'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26',
       'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30',
       'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34',
       'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38',
       'Soil_Type39', 'Soil_Type40'],
      dtype='object')

In [26]:
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.datasets import make_friedman1
from sklearn.ensemble import GradientBoostingRegressor

X=tr.values
print (X)


Y=np.array(fr['Cover_Type'])
print (Y.shape)

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=1000)
clf = clf.fit(X, Y)
clf.score(X,Y)

[[2596   51    3 ...,    0    0    0]
 [2590   56    2 ...,    0    0    0]
 [2804  139    9 ...,    0    0    0]
 ...,
 [2492  134   25 ...,    0    0    0]
 [2487  167   28 ...,    0    0    0]
 [2475  197   34 ...,    0    0    0]]
(15120,)

1.0

In [27]:
test=pd.read_csv("test.csv")

In [28]:
test.describe()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
count,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,...,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000,565892.000000
mean,298066.500000,2964.977407,155.629558,14.039635,270.556622,46.294408,2367.143116,212.131133,223.435026,142.726951,...,0.044768,0.091588,0.078704,0.002808,0.003161,0.000193,0.000467,0.026233,0.023236,0.014651
std,163359.093604,273.157030,111.962120,7.450155,212.500153,58.209469,1561.482002,26.661063,19.668053,38.030094,...,0.206795,0.288444,0.269277,0.052916,0.056137,0.013877,0.021594,0.159827,0.150652,0.120152
min,15121.000000,1859.000000,0.000000,0.000000,0.000000,-173.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,156593.750000,2818.000000,58.000000,9.000000,108.000000,7.000000,1116.000000,198.000000,213.000000,119.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,298066.500000,2999.000000,127.000000,13.000000,228.000000,29.000000,2018.000000,218.000000,226.000000,143.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,439539.250000,3164.000000,260.000000,18.000000,390.000000,69.000000,3349.000000,231.000000,237.000000,168.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,581012.000000,3858.000000,360.000000,66.000000,1397.000000,601.000000,7117.000000,254.000000,254.000000,254.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
te=test.drop(columns=['Id'])

In [30]:
s=te.values

In [31]:
q=clf.predict(s)
q

array([2, 1, 2, ..., 3, 3, 3])

In [32]:
q=np.around(q,decimals=0)

In [33]:
q

array([2, 1, 2, ..., 3, 3, 3])

In [34]:
ans={
    
    'Id':test['Id'].values,
    'Cover_Type':q
    
}

In [35]:
df=pd.DataFrame(ans)

In [37]:
df.Cover_Type=df.Cover_Type.astype(int)
df

        Cover_Type      Id
0                2   15121
1                1   15122
2                2   15123
3                2   15124
4                2   15125
5                2   15126
6                2   15127
7                1   15128
8                1   15129
9                2   15130
10               1   15131
11               1   15132
12               1   15133
13               2   15134
14               2   15135
15               2   15136
16               2   15137
17               2   15138
18               2   15139
19               2   15140
20               2   15141
21               2   15142
22               2   15143
23               1   15144
24               1   15145
25               1   15146
26               1   15147
27               1   15148
28               1   15149
29               2   15150
...            ...     ...
565862           3  580983
565863           3  580984
565864           3  580985
565865           3  580986
565866           3  580987
565867           3  580988
565868           3  580989
565869           3  580990
565870           3  580991
565871           3  580992
565872           3  580993
565873           3  580994
565874           3  580995
565875           3  580996
565876           3  580997
565877           3  580998
565878           3  580999
565879           3  581000
565880           3  581001
565881           3  581002
565882           3  581003
565883           3  581004
565884           3  581005
565885           3  581006
565886           3  581007
565887           3  581008
565888           3  581009
565889           3  581010
565890           3  581011
565891           3  581012

[565892 rows x 2 columns]

In [38]:
df.to_csv("ans.csv",columns=['Id','Cover_Type'],index=False)